### ISSUE TITLE
Support sharing preferences between computers

### ISSUE THREAD

**Issue by rahatarmanahmed** [surjikal/sublime-coffee-compile#41]
I sync the same Packages/User directory between my Windows PC and Macbook. This means my coffee binary is located in two different places, but this package's config is shared between the two computers, so only one can work at a time.

I'm not sure exactly how ST package development works, but is it not possible to infer the binary location from the PATH? If not, can you allow specifying multiple paths in the config, using the first one that works?

**Comment by surjikal** [comment]
Yeah, if I recall correctly the python interpreter is sandboxed and I don't have access to the `PATH` variable. That's why the binary needs to be specified in the config file. Your second solution would work well! Are you able to give me a pull request?

**Comment by rahatarmanahmed** [comment]
Sorry, I don't really know much about Python or ST package development.
