### ISSUE TITLE
Coffee path are configured properly but compile doesn't work 

### ISSUE THREAD

**Issue by cbaeza** [surjikal/sublime-coffee-compile#43]
Coffee path are configured properly but compile doesn't work 
OSX Yosemite, Sublime build 3065

Command line > which coffee
   /usr/local/bin/coffee
------- CoffeeCompile.sublime-settings ----
{
	"coffee_path": "/usr/local/bin/coffee",
	"coffee_executable": "coffee"
}
------ Error ----------
# CoffeeCompile Error :(

Could not find your `coffee` executable...
Your `coffee_path` setting is probably not configured properly.

To configure CoffeeCompile, go to:
`Preferences > Package Settings > CoffeeCompile > Settings - User`

## Details
```
FileNotFoundError(2, "No such file or directory: 'coffee'")
```

## Halp
If you're sure that you've configured the plugin properly,
please open up an issue and I'll try to help you out!

https://github.com/surjikal/sublime-coffee-compile/issues

## Path
```
/usr/local/bin/coffee
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by surjikal** [comment]
Try to set the coffee_path to `/usr/local/bin` instead of `/usr/local/bin/coffee`.

**Comment by cbaeza** [comment]
Hi Guys, thanks a lot. I have changed my path to 
    "coffee_path": "/usr/local/bin"
and work all fine.
Thanks
