### ISSUE TITLE
FileNotFoundError despite following settings instructions

### ISSUE THREAD

**Issue by manova** [surjikal/sublime-coffee-compile#45]
My current user settings is as follows:
```
{
    "coffee_path": "/usr/local/bin",
    "compiler": "vanilla-executable"
    "coffee_executable": "coffee",
    "node_path": "/usr/local/bin"
}
```
However, I still get the error ```FileNotFoundError: [Errno 2] No such file or directory: 'coffee'``` every time I try to compile. Any pointers would be great.

**Comment by surjikal** [comment]
Your `coffee_path` is probably not right.

On my machine, my coffee executable is under the `/usr/local/share/npm/lib/node_modules/coffee-script/bin` directory.

**Comment by manova** [comment]
I found out the problem comes from the ```coffee_compile``` command not being visible in Sublime Text 3 so I had been using the Better CoffeeScript command all along. I fixed this by adding the file ```CoffeeCompile.sublime-commands``` to the base project directory with the following content:

```
[
    {
      "caption": "CoffeeCompile: Compile File",
      "command": "coffee_compile"
    }
]
```

I can put this in a pull request if you think this wouldn't hurt support for ST2.
